name: GNU Guile 2.2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
              automake \
              autoconf \
              guile-2.2 \
              guile-2.2-dev \
              guile-library \
              texinfo

      - name: Install Guile-SMC
        run: |
          git clone https://github.com/artyom-poptsov/guile-smc
          cd guile-smc
          autoreconf -vif
          ./configure --with-guilesitedir=/usr/share/guile/site/2.2
          sudo make -j2 install

      - name: Checkout repository 
        uses: actions/checkout@v2

      - name: Autoreconf
        run: autoreconf -vif

      - name: Configure
        run: ./configure

      - name: Build
        run: make

      - name: Run tests
        run: make check

